remote_theme: chromatical/jekyll-materialdocs

title: EOSC Governance Framework
description: EOSCPilot Deliverable D2.6 (Governance framework for a European Open Science Cloud)
copyright:
logo: assets/eoscpilot-logo.png
url: "https://europeanopensciencecloud.github.io"
baseurl: "/Governance"
highlight: rouge
mdl_colors: light_blue-blue
search: true
menu_style: dropdown

# Build settings
markdown: kramdown

plugins:
- jekyll-remote-theme
